README.md
Removes prettier from the README since we're just using eslint in the repo for now.
=> docs: remove prettier

.eslintrc.js, components/TopNav.vue, pages/index.vue
- disable `vue/multi-word-component-names` rule as per conversation with @ann-kilzer on slack
- add default value to prop where required
run `yarn lint` and 0 warning should appear.
=> Fix eslint warnings

.husky/commit-msg, commitlint.config.js
Resolves #41 
See https://www.conventionalcommits.org/ and https://github.com/conventional-changelog/commitlint
run following:
- `yarn && yarn prepare`
- `touch bar && git add bar && git commit -m 'foobar'`
output should be similar to below:
```
$ git commit                                    
⧗   input: foobar
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
```
=> feat: add git hook to enforce conventional commit

.github/ISSUE_TEMPLATE/default.md
=> DOCS: Create default issue template

.eslintrc.js
Part of #137 
Warn when blocks are not using typescript
Run `yarn lint` on the branch, should see: 
```sh
.../ourjapanlife/findadoc-web/components/SearchBar.vue
53:1  warning  The 'lang' attribute of '<script>' is missing  vue/block-lang
.../ourjapanlife/findadoc-web/components/SearchResult.vue
23:1  warning  The 'lang' attribute of '<script>' is missing  vue/block-lang
.../ourjapanlife/findadoc-web/components/SearchResultsList.vue
22:1  warning  The 'lang' attribute of '<script>' is missing
```
=> feat: add typescript check to vue block

.eslintrc.js, components/SearchBar.vue, components/SearchResult.vue, components/SearchResultsList.vue
Resolves #137 
- turn up eslint to error
- add typescript to scripts
- linter should pass
- code should build and run
Note I had some hiccups with the VS Code extension "Vetur" complaining about the vue import, but since that is a very sluggish tool and geared to Vue 2, I removed it and am fully on Volar. [See this thread.](https://stackoverflow.com/questions/54839057/vscode-showing-cannot-find-module-ts-error-for-vue-import-while-compiling-doe)
=> Enforce Typescript on scripts

components/SearchBar.vue, components/TopNav.vue, cypress/e2e/home.cy.ts
Part of #169 and resolves #151
- Create some skeleton tests for cypress (will be easier to divvy up among contributors)
- Adjust Logo to emphasize "Find a Doc" and read more naturally
Confirm the logo looks like this:
Confirm the cypress tests pass: `yarn run test:e2e`
=> cypress skeleton tests + logo adjustment

netlify.toml
Resolves #206 
- check if the netlify build works now. 
-  https://app.netlify.com/sites/findadoc/deploys/63f313f939e9550c4d3f5a21
=> BUGFIX: fixing netlify production build error

.eslintrc.js, package.json, typedefs/gqlTypes.ts, typesgeneratorconfig.ts, yarn.lock
Resolves #204 
- run `yarn generate` and it should work. the `typedefs/gqlTypes.ts` file will update with any changes
=> feat: generating types from gql api

components/TopNav.vue, i18n/locales/en.json, i18n/locales/ja.json, pages/submit.vue, stores/localeStore.ts, stores/submissionStore.ts
Creates a Submit page with form that will eventually allow users to submit a healthcare professional to the platform. For now, it just console logs the submission until work is completed on the backend to add additional locales.
=> Create Submit Page

components/SearchBar.vue, components/TopNav.vue
MVP UI Fixes
- fixes site logo resizing and responsiveness
=> MVP UI Fixes

components/HamburgerComponent.vue, components/TopNav.vue, i18n/locales/en.json, stores/menuStore.ts
Adds a breakpoint for md size screens so only the hamburger menu is shown on smaller screens. Further improvements will need to be made to display the search filters on mobile, and have the overall UI look and flow as depicted on [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1207-9553&mode=design&t=yirhFIMLVvD6Wkwb-0).
This is just a 🩹 and a lot more work on the top nav will be needed!
=> fix: make top nav responsive

utils/apollo.ts
Resolves #330
updating the api url to point to `api.findadoc.jp` instead of the `/api` route
=> updating the api url

components/SearchResultsList.vue
Resolves #341
Small fix. The SearchResultList was not showing all the healthcare professionals since it was hidden.
Before:
After (kept the dev layout on) :
I have added a flex on the outer div of the SearchResultList component.
=> Fix SearchResultList component partially hidden

pages/index.vue
This PR is part of a 🥞
1. https://github.com/ourjapanlife/findadoc-web/pull/352 👈🏼 You are here
2. https://github.com/ourjapanlife/findadoc-web/pull/351
3. https://github.com/ourjapanlife/findadoc-web/pull/353
Root template in Vue/Nuxt require exactly one element. This wraps the temporary Beta Banner and the other components in one `div`.
View the preview of the site and ensure that the UI hasn't changed.
=> fix: contain root template in one element

components/HamburgerComponent.vue, components/MainContentContainer.vue, components/TopNav.vue, nuxt.config.js, pages/index.vue
Resolves #347 
This PR is part of a 🥞
1. https://github.com/ourjapanlife/findadoc-web/pull/352 
2. https://github.com/ourjapanlife/findadoc-web/pull/351 
3. https://github.com/ourjapanlife/findadoc-web/pull/353 👈🏼 You are here
Creates different layouts based on whether or not the screen is larger or smaller than a tablet.
See the mobile design on [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=704-12700&mode=design).
Click the Netlify preview in the comment below, and resize the page to mobile and check that it's responsive.
=> fix: add breakpoints to make site usable on mobile

components/MainContentContainer.vue, components/MapContainer.vue, pages/index.vue
Part of #347 
- I have refactored the Mapcontainer component. In Vue3 we can add the `setup` in `<script>`. Since we are doing this in the other components it seemed better for consistency.
- To make the the map visible in desktop, I have changed some tailwind elements. During testing and reviewing I have notice that some elements were  unnecessary and have removed them.
=> Make the map visible again on desktop

.stylelintrc, eslint.config.js, package.json, yarn.lock
Resolves #378 
1. I have added the Stylistic plugin to our ESlint config file, and used it to implement our formatting rules.
2. I have removed the formatting rules in our Stylelint config file.
ESlint and StyleLint have deprecated there formatting rules. At the moment I don't have a solution yet for the formatting rules in StyleLint, I need to do some more research.
Here you find the deprecated formatting rules for StyleLint: https://stylelint.io/migration-guide/to-15/
Here you find the deprecated formatting rules for ESlint: https://eslint.org/blog/2023/10/deprecating-formatting-rules/
=> Migrate formatting rules for ESlint and StyleLint.

package.json
Removes the `yarn start:test` script that is no longer used to run tests.
=> chore: remove start:test script that is no longer used

.github/workflows/cypress.yml
Prior to this PR, the GitHub CI was failing to run the Cypress tests, because the workflow was looking for a command we no longer use. It was returning an error such as the following:
```
Usage Error: Couldn't find a script named "build".
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```
Click the "Details" button for the Cypress e2e tests in the GitHub CI. Confirm that the tests are being ran instead of seeing the error message above.
=> fix: update build and start commands for cypress workflow

test/functional/modalStore.spec.ts
Prior to this change the Vitest/Pinia workflow was failing because there weren't any tests to run. This change introduces a test for the workflow to execute and no longer fail.
=> fix: add test for modal store to fix failing vitest workflow

renovate.json
This change limits the number of PRs Renovate bot can open to 3. This should greatly reduce the number of open PRs we have at a given time.
It also sets the admin team members as the reviewers that the bot should tag.
=> chore: add PR limit and reviewers to renovate bot

.github/pull_request_template.md
Adds a "Screenshots" section the PR template to help devs to remember to include Before and After screenshots for UI changes that are made.
=> docs: update PR template to include screenshots

assets/images/email-icon.svg, components/SearchResultDetails.vue
Resolves #336 
Previously a facility's email address was not displayed in the `SearchDetailsResult`. This renders the email.
1. Implemented logic to conditionally display the facility's email address.
2. Added an SVG icon for email addresses.
3. Email addresses with a value of `none` or `email@email.com` are filtered out with a `v-if` statement. (See the images below. I can remove this if necessary.)
Open the app, click on a doc and check out their email!
=> feat: Add email address to SearchResultDetails

test/functional/loadingStore.spec.ts
Part of #395 
This PR adds Pinia tests to test the functionality of the loadingStore.
Run `yarn test:pinia` and confirm that the loadingStore tests pass.
=> test: add tests for loadingStore

components/SearchResultDetails.vue, components/SearchResultsList.vue, components/SearchResultsListItem.vue
previously the degrees were not displayed anywhere on the SearchResults
Resolves #335 
- Before there were no degrees displayed in either the SearchResultsList or the the SearchResultDetails. 
- The first degree is show with an ellipsis and number of degrees that are not shown in the List.
- In the details, the full list of the doctor are shown.
- The unnecessary comma in the Romaji names was removed.
- Currently there are no tests for this
-   ### Before
-   ### After
- Create tests for the changes in the components
=> Add healthcare professional degrees to SearchResultDetails

test/functional/localStore.spec.ts, vitest.config.ts
Resolves #395 
- I have added the basic tests for `localeStore`
- I have added an extra path in the vitetest config file, so it could recognize `~`
Run `yarn test:pinia`
- Add testing for types?
=> Add tests for localeStore

components/SearchResultDetails.vue
Resolves #368 
Previously, if a professional's profile only contained a Japanese name (and vice versa) and the user switched the language locale to anything other than Japanese, the name would appear empty or undefined. Now it also shows a name when toggle to Swahili.
1. I have refactor the conditional statement, by using a switch case.
Currently we actually don't have a professional that misses a English name or Japanese name. But if you want to test it please change the following  variables and toggle the locale:
```
const englishFullName = undefined
const japaneseFullName = `${japaneseName?.lastName} ${japaneseName?.firstName}`
```
=> Debug undefined name when name does not exist in locale language.

pages/submit.vue
Resolves #431 
The margin on the bottom was zero so t bottom was zero so the ‘footer' was right up against the component. It needed 
N/A
-   ### Before
-   ### After
=> style: add margin on bottom

package.json
Resolves #437 
We were still using the old `husky install` command. I have updated the command to the version 9 command `husky`.
Documentation v9: https://github.com/typicode/husky/releases/tag/v9.0.1
run `yarn prepare` should not get an error anymore.
=> Change the husky install command.

.husky/pre-push
Resolves #438 
(This PR should have been part of https://github.com/ourjapanlife/findadoc-web/pull/438)
I have updated the husky file to the new v9 standard. See documentation: https://github.com/typicode/husky/releases/tag/v9.0.1 
Since this file only triggers when you make push, please try to make a small changes to the husky file (add extra star emoji to like this `echo "✨linting ✨"` . And see if the husky file is running when you push.
=> Update husky file to v9 standard.

nuxt.config.js, pages/moderation.vue
Resolves #461 
- Before there was no route for the moderation panel, but the route `/moderation` was added.
- It conditionally renders the page when `ENABLE_MODERATION_PANEL=true` is in `.env` file.
-   ### After
=> feat: add page for moderation panel

app.vue, components/ModLeftNavbar.vue, components/ModMainContent.vue, components/ModTopbar.vue, pages/moderation.vue, stores/moderationScreenStore.ts
Resolves #466 
In this PR we have created the layout for the components of the moderation panel.
- Create components for modTopBar, modMainContainer and modLeftNavbar
- Create store for managing the state for switching between our dashboard screen an review submission screen
- Create the basic layout by adding basic styling
=> Add layout component for moderation panel

stores/moderationScreenStore.ts
Resolves #471 
Before `enableModerationPanel` was hardcoded to false instead of checking the `env` file for the variable that sets it to true that allows us to see it in development.
-   ### Before
-   ### After
=> fix: add runtime config variable to store

components/ModMainContent.vue, components/ModSubmissionListContainer.vue
Resolves #455 
Before there was no main component for us to hold the submissions. This created a list component that can hold the data based on the state and will change what is displayed under the heading based on what is clicked in the dashboard. There is commented out code to show how it can be implemented in the future to use data to preview the data we want. We will set the data it is looping through based on the states in the sidebar component that in the future will run a function that can filter the data based on the states.
The grid system was chosen due to recommendations to avoid semantic tables from @ermish due to css problems that could arise.
-   ### Before
-   ### After
=> feat: implement main container for submission

components/SearchResultDetails.vue, components/SearchResultsList.vue
This PR will change it so that facility names will be shown in romaji for locales other than Japanese. Currently, if someone selects Swahili from the dropdown button, it will show all of the details in English except for the facility name. English should be the default, because there's a high chance that users will be unable to read Japanese.
Select Swahili from the dropdown menu and confirm the following:
1. The facility name is shown in romaji in the search results list
2. The facility name is shown in romaji in the search result details card
-   ### Before
-   ### After
=> fix: display facility data in romaji for non-JaJp locales

stores/submissionStore.ts
We removed the `variable` key from the input, because we noticed on the backend that it was creating an additional nested key for one that already exists.
1. Run the backend dev db using `npm run dev:startlocaldb`
2. Run the backend dev server using `npm run dev`
3. Point the frontend endpoint to the backend server
4. Fill out the Submit form on the local frontend server and verify the payload that prints in the backend console.
=> fix: remove duplicate variable key breaking submit page

app.vue, components/HamburgerComponent.vue, components/MainContentContainer.vue, components/MapContainer.vue, components/TopNav.vue, i18n/locales/en.json, pages/about.vue, pages/index.vue, pages/privacypolicy.vue, pages/submit.vue, pages/terms.vue, stores/menuStore.ts
When a user is viewing the site on a desktop, the TopNav and Footer should always be visible without having to scroll. Meaning, the main content should be contained between them and be the only component that scrolls up and down.
This behavior wouldn't work that great on tablet and mobile screens due to their much smaller sizes. So, some adjustments were made to what items will be displayed depending on what screen size the user is using.
1. Makes the TopNav and Footer always visible on desktop
2. Makes the TopNav display the HamburgerComponent on screens smaller than desktop. This remedies the issue of menu items overlapping for sizes between tablets and desktop.
3. Creates separate menu items for the hamburger menu. Items that were previously included in the footer were moved here, but …
=> fix: improve responsiveness and component visibility

stores/submissionStore.ts
Part of #502 
Small PR that wraps the Submit request in a try/catch. Further changes are currently being made in #494 to add Cypress testing for the page. Validation will also be added in a separate PR.
=> chore: wrap submit request in try catch

README.md
Removes mention of tech we no longer use in the README.
=> docs: remove unused tech from README

pages/index.vue, pages/submit.vue
Fixes a couple small scrolling bugs that appeared in prod but not in #493
1. Check that the footer is stationary on desktop in the preview for Home and Submit pages.
2. Check that the Submit page is full width.
-   ### Before
-   ### After
=> chore: fix scrolling and page width

components/ModDashboardLeftNavbar.vue
The images were not appearing properly due to the change of the `svg` from img to component style. Updated to be the way we import the `svg` now
-   ### Before
-   ### After
=> fix: change the old import to new style

pages/moderation.vue, stores/moderationScreenStore.ts
Before we were handling the visibility of the route for  `/moderation` with only and environmental variable which is mocking the feature flag variable for now. This now conditionally handles the variable and the visibility of the route with not only the `env` variable being set to true, but if the `pathname` includes `moderation`. I implemented it this way in case we have nested routes later.
-This will allow for successful testing of moderation panel testing in the future since it will not change the layout of the other pages, which would cause all those cypress tests to fail
-   ### Before
-This is how the layout was being affected before.
-   ### After
This is what it looks like with new implementaiton
-Moderation panel still displays
=> fix: change handling of mod store visibility to use path

package.json, utils/graphql.ts
This adds a new command to the package.json that can be used to connect the FE to findadoc-server when a dev is running it locally.
1. Follow the steps in the findadoc-server repo to start the Firebase database and backend server locally.
2. Start the frontend server using the `yarn dev:localdb` command.
3. Confirm that the FE displays data from the local database.
=> feat: add conditional for local server endpoint

.github/workflows/cypress.yml, cypress/e2e/moderationDashboard.cy.ts, cypress/e2e/submit.cy.ts, package.json, yarn.lock
Part of #540 
1. This PR adds `.skip` to the test that is making fake submissions to the prod database. We'll re-enable this once we figure out mocking. 
2. This PR also changes `.blur()` in tests to `.tab()` because the command was causing Cypress to fail consistently. The purpose of the blur was to make the error messages appear, but it also had the effect of changing the DOM. The [cypress-plugin-tab](https://github.com/Bkucera/cypress-plugin-tab) allows us to use tabs in our tests, which is helpful for triggering the input validations.
3. Increases the wait time between moderation tests that were failing due to the elements not having enough time to load.
4. Upgrades the [Cypress Github Action](https://github.com/cypress-io/github-action) to (hopefully) fix the "server not running" …
=> refactor: update problematic tests

components/MainContentContainer.vue, components/SearchResultsList.vue
Currently, it's difficult for users to understand when there are no search results. The information is rendered off screen on mobile in both portrait and landscape mode. This PR improves the visibility of the "No Results Found" message on mobile, so most users will be aware that it's there without having to scroll. 
It also improves the visibility of the Search Results List, by enabling users to scroll to the bottom of the last result. For iPhone users, this information is currently blocked by the toolbar.
1. Test the preview on an iPhone in portrait and landscape mode.
2. Test the preview on a desktop browser and drag the size.
Desktop before
Desktop after**
Mobile landscape before:
Mobile landscape after:
Mobile portrait before:
Mobile portrait after:
=> refactor: improve visibility of search results

components/SubmissionForm.vue
Resolves #543 
This PR makes it possible to scroll to the Submit button at the bottom of the Submit page without affecting the visibility of the sticky menu.
1. Open the preview on an iPhone (must be an actual phone).
2. Scroll to the bottom and confirm that both the sticky menu and Submit button are visible at the same time.
https://github.com/ourjapanlife/findadoc-web/assets/31802656/213c19ff-923f-4d45-a09c-337abcd55b9c
https://github.com/ourjapanlife/findadoc-web/assets/31802656/e49466ef-3074-4fff-bb69-591304d287fe
=> chore: add margin to bottom of submit component

cypress/e2e/submit.cy.ts
Increases the wait time before each Submit validation test, because sometimes the elements are slow to load. This was failing on `main` for #534, but passed after re-running it.
=> chore: increase wait between submit tests

typedefs/gqlTypes.ts
This updated the generated types based on the graphQl schema change.
Locally build the production and see that the types are the same as seen in the PR using 
```
yarn prod:build
```
=> chore: update generated types on db schema

stores/moderationSubmissionsStore.ts
Resolves #578
The query before did not include the `mapLatitude` or `mapLongitude` as part of the graphQl query since it was just added to the backend. This needs to be added in order to autofill forms once they have been updated.
Start your backend with 
```
npm run dev:startlocaldb
npm run dev
```
Then run 
```
yarn dev:localserver
```
You should be able to successfully query the db and get the mapLatitude and mapLongitude
=> chore: update submission query to match schema

cypress.config.ts, cypress/e2e/about.cy.ts, cypress/e2e/home.cy.ts, cypress/e2e/moderationDashboard.cy.ts, cypress/e2e/submit.cy.ts
Currently, tests are failing assertions for certain elements—some that are not rendering, and some that are offscreen. I discovered that the screen size can change between tests if it's only specified in the `before()` and not the `beforeEach()`. This was causing failures when looking for specific elements in either portrait or landscape mode.
1. Run `yarn dev`
2. Run `yarn cypress run`
3. Confirm that the tests are passing
Additionally:
1. Run `yarn cypress open`
2. Run each e2e test and confirm that the tests are running against the proper screen resolutions
1. Run `yarn prod:build`
2. Run `yarn prod:start`
3. Run `yarn cypress run` to confirm that the tests pass.
4. Follow the Additional steps above
=> refactor: adjust screen resolutions and wait times for submit tests

.github/CODEOWNERS
[Documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax)
Currently, developers are able to merge PRs that are approved by any contributor on the repository. This is due to changes that were made in #240 with improper syntax. This changes it to (hopefully) require code owner approval as intended.
=> fix: fix syntax for CODEOWNERS

cypress/e2e/about.cy.ts, cypress/e2e/privacy.cy.ts, cypress/e2e/submit.cy.ts, cypress/support/commands.js
This change removes the custom `isInViewport` and `isNotInViewport` commands. They were introduced as a way to ensure that the top navigation and footer were always visible without scrolling. However, they are conflicting somehow (possibly with webpack) when CI is ran through the Github Actions.
1. Run `yarn dev`
2. Run `yarn cypress run` and confirm the tests _pass_
=> refactor: remove isInViewport and isNotInViewport

components/LocaleSelector.vue
This was mentioned a while back by @Ntlja. She noticed that our selects were not consistent in styling. So this updates the `LocaleSelector` to use the same styling as the `SearchBar` in terms of padding. I kept the styling in the hamburger menu the same due to it being styled in a way that fits into the hamburger menu text sizing.
Run `yarn dev` and confirm it matches the screenshots
-   ### Before
Mobile:
-   ### After
Mobile:
=> style: match styling of language select to searchbar

components/ModDashboardLeftNavbar.vue, cypress/e2e/moderationDashboard.cy.ts, typedefs/gqlTypes.ts
Resolves #509 
In the submission dashboard there is a count for how many of each type of submission there are based on its status in the database for approved, rejected, or under review. Now it is dynamically calculated and tested based on the Boolean from the database.
You can go to the branch and run:
```
yarn dev
yarn cypress open
```
From here you should run the `moderationDashboard.cy.ts` specs. They all should pass.
-   ### Before
-   ### After
=> feat: implement autofill for counts

components/ModDashboardLeftNavbar.vue, components/ModSubmissionListContainer.vue, cypress/e2e/moderationDashboard.cy.ts, stores/moderationSubmissionsStore.ts
Resolves #508 
Before we would show all the different types of submissions in the `SubmissionListComponent`. Now it is filtered based on which tab is selected.
There are tests added so you can go to the branch and run
```
yarn dev
yarn cypress open
```
and then run the `moderationDashboard.cy.ts` spec
-   ### Before
https://www.loom.com/share/cec042893b6c476881e3b398f76f6fc4
-   ### After
https://www.loom.com/share/6f2c0e990acc403fae1203b38e061e6e
=> feat: show filtered data in ModSubmissionList

components/FadeInTransitionImage.vue, components/MemberComponent.vue, cypress/e2e/about.cy.ts, pages/about.vue
This component can be used anywhere in the app. It allows for a smoother load of images no matter the size. Even after compressing the about us files they would sometimes load in a manner that was less than ideal. Now it should load with a fade in effect if there is a delay or load the whole image at once.
Go to the branch and run:
```
yarn dev
yarn cypress open
```
-   ### Before
https://www.loom.com/share/28505cfdc1d44891993686e793a64c29
-   ### After
https://www.loom.com/share/9fc53ffec9aa4122a7bf8f933379f096
=> feat: implement transition for fade-in images

components/SubmissionForm.vue, cypress/e2e/submit.cy.ts, i18n/locales/en.json, i18n/locales/ja.json, i18n/locales/pt.json, utils/formValidations.ts
Resolves #623 
Before error messages were displayed before the user left the field and only showed when correct. The logic is now changed to reflect the same way we used in the Moderation Panel Form. We validate on blur for the first entry. Then we validate on change until it is correct. We also have an extra check on submit to validate.
The tests should not have changed. They are the same as before with the submissions. Only error showing logic has changed.
-   ### Before
-   ### After
https://www.loom.com/share/2d1500f2fb9b4f0b801911c389c41a06
=> refactor: implement new error logic in submission form

pages/index.vue, utils/useScreenOrientation.ts
Resolves issue #640
I made a composable. This can use screen orientation to set variables and then improve the responsiveness of the app on mobile.
##Details
As you can see I used my phone to record the video of the deployed preview from a ticket without this change and with this change and the layout is correct instantly on the after video
The tests should still pass since it didn't change functionality.
-   ### Before
https://github.com/ourjapanlife/findadoc-web/assets/124335161/b1a664bc-9203-400a-a6ed-5018bf76db4e
-   ### After
https://github.com/ourjapanlife/findadoc-web/assets/124335161/9af45665-a7e0-4927-8ab5-0c7f19011b82
=> feat: create composable to check viewport

components/MainContentContainer.vue
Resolves #213 
The Modal (bigger than tablet mode)
a)is not overlapping with the footer and 
b)scrollable IF the winodw height is too narrow
1. Open browser
2. open dev tools
3. set the website to a screensize bigger than tablet
4. narrow the height 
-   ### Before
-   ### After
https://github.com/user-attachments/assets/600e7745-d98a-44b9-b414-f301c97f7b3c
=> FIX(UI): overlapping modal with footer for desktop users

cypress/e2e/about.cy.ts, cypress/e2e/home.cy.ts, cypress/e2e/moderationDashboard.cy.ts, cypress/e2e/privacy.cy.ts, cypress/e2e/submit.cy.ts
Resolves #662 
The tests were using `cy.wait` to make sure pages were visited and components had time to render. Now the build in timeout method is used. This is designed by Cypress in order to move on right when the test passes. `cy.wait` Takes the whole time.
Build the production locally and run the tests on this branch. Check the timing. Check that also on another branch and compare the times.
-   ### Before
This is from another branch I recently re-ran
-   ### After
This if from the new CI/CD
=> test: improve test speed for ci/cd pipeline

cypress.config.ts, cypress/e2e/home.cy.ts, cypress/e2e/moderationDashboard.cy.ts, cypress/e2e/submit.cy.ts
Resolves #660 
A timeout was added to the `cypress.config.ts` in order to avoid CI/CD failures in the pipeline of Cypress e2e tests just due to a timeout of finding the localhost
No tests were fundamentally changed
-   ### Before
N/A
-   ### After
N/A
=> fix: add timeout to cypress config for ci timeout

cypress/e2e/moderationDashboard.cy.ts
Resolves #664
In the tests the intercept was being registered on the return from the auth login. But this could possible happen before or after the website in production had return to `localhost:3000`. Now the url is checked with a timeout to ensure that the intercept can register properly on the frontend.
Tests run successfully
N/A
=> fix: change intercept order to confirm route registration

components/ModEditSubmissionTopbar.vue, stores/moderationSubmissionsStore.ts, utils/graphql.ts
Resolves #639 
Related to #636
This implements the functionality of the reject button to reject a facility submission. Before it just logged. Now if I click, the facility will be rejected and moved in tabs.
It also contains a custom function that will allow us to pass `GQL requests` and retry recursively.
1.  Run the local backend 
```
yarn dev:startlocaldb
```
```
yarn dev
```
2. Then start the frontend 
```
yarn dev:localserver
```
3. Reject a submission and you can see how it changes as shown in the After screenshot
-   ### Before
-   ### After
This is the submission list before I reject Stephanie Mills
and after with the rejection seen in the separate tab
=> feat: implement mutation rejection for facility submission

components/ModEditSubmissionForm.vue, stores/moderationSubmissionsStore.ts
Resolves #701
Before the `ModEditSubmissionTopBar` was not working for Save & Exit. As well as this the submission itself wasn't working due to the variable name not matching what was expected. Now it is updated to Save and Exit successfully from the Top Bar. Otherwise if you press enter or just submit it doesn't automatically exit so you can keep working on the form.
Go to the backend and start the localdb with
```
yarn dev:startlocaldb
```
and start the backend with
```
yarn dev
```
Then start the frontend with 
``` 
yarn dev:localserver
```
-   ### Before
N/A
-   ### After
https://github.com/user-attachments/assets/f5124c5a-7554-4a7a-aa70-d6c7f2449978
=> fix: add id missing in update submission

components/SearchResultsList.vue, cypress/e2e/home.cy.ts
Resolves #716 
The `SearchResultsList.vue` container wasn't scrollable on auto! Our users could not see all the doctors.
Tests were added to the home page to ensure that in portrait and landscape you can scroll to the bottom of the search list container and see the last item.
-   ### Before
https://github.com/user-attachments/assets/074713ea-10ec-40e3-a004-26fc5e04970c
-   ### After
https://github.com/user-attachments/assets/b149c2a5-6044-4357-b3a6-c1d3dc6b4c49
=> fix: style overflow y to auto on search results list

stores/modalStore.ts
Resolves #733 
We refactored the modalStore from option store to setup store using loadingStore as an example to follow.
=> chore: change modalStore into Vue setup store

components/SearchResultsListItem.vue, stores/localeStore.ts, test/functional/localeStore.spec.ts
Resolves #723 
The function that made the locales more readable was written within the file. But I already found a use case in the mod panel where we would want to make it more readable. So it was moved out to the `localeStore` where localization is handled and made reusable.
Tests were written for the Pinia tests in `localeStore.spec.ts` so you can run the tests in this file
N/A as there is no change to the actual design of the website
=> refactor: implement format function in store for locales

components/Modal.vue
In the modal changed the attribute of the type to `button`
=> chore: change modal to type button

components/ModEditSubmissionTopbar.vue
Updated the button type in the `components/ModEditSubmissionTopbar.vue` to `type="button" to avoid unwanted behavior on clicks.
=> refactor: update button type

components/ModInputField.vue
Resolves #760 
Before the validation check was required. But not every field on the form will always be required. For instance, in Japan middle names are rare but are optional when accepting a doctor or submission. This reworks the logic for the validation check in order to fit the reusability within the moderation panel.
=> refactor: remove required validation check from mod input

components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue, stores/moderationSubmissionsStore.ts
Before the variable names in the store were reading `mutation` and `query`. It wasn't desirable to name a ref the same as the actual API calls, so it was updated to be a name that fit with what the variable is doing and then updated where the variables were being previously used.
=> fix: improve variable names in submission store

modules/vue-toastification-module.ts, nuxt.config.js
This refactors the toast to be a module in the nuxt config instead of in the build for consistency.
=> refactor: change toast from build to module in config

components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue
This is part of breaking out #718  into smaller PRs. This implements the Modal showing from the top bar when accept is clicked, so that you can confirm that you actually want to submit the facility into the database and you are sure about the changes you made. This keeps the user from accidentally submitting when on the page with a mis click.
=> feat: implement modal for submission acceptance

.github/pull_request_template.md, .github/workflows/lint-pr-title.yml, README.md
We'd like to ensure that commit messages that go into main are consistent and high quality. Since we use the "squash and merge" setting, the PR title is what becomes the commit message when it is merged. This workflow will check that the PR title follows [conventional commit specifications](https://www.conventionalcommits.org/en/v1.0.0/).
[Workflow documentation](https://github.com/amannn/action-semantic-pull-request)
[Slack discussion](https://find-a-doc.slack.com/archives/C02663QK8TD/p1727925045163499)
=> feat: add workflow for validating pr titles

stores/searchResultsStore.ts
Resolves #810 #810
1. This file had duplicate imports in the store from the `typeDefs/gqlTypes` file and they were removed. 
2. It was missing the import `gqlClient` and this was added.
=> chore: update imports in `searchResultsStore`

components/ModDashboardLeftNavbar.vue, components/ModDashboardTopbar.vue, components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue, components/ModInputField.vue, components/ModMainContent.vue, eslint.config.js, i18n/checkLocaleKeys.js, stores/localeStore.ts, stores/searchResultsStore.ts, utils/formValidations.ts
There are several lines in our codebase that exceed the maximum length of 130. Most of them are because refs are treated as strings. This change to the eslint config will make it so lines with strings must also be 130 characters or less. The `/cypress` director was added to the ignore list, because it tests long urls that are not treated as strings.
=> chore: configure eslint to not ignore strings for max length

components/ModEditSubmissionForm.vue, cypress/e2e/moderationDashboard.cy.ts, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json
Related issue: #771
This PR refactors the `modEditSubmissionForm` component so that the modal only shows if a user hits the back button and has unsaved changes.
In your local environment: 
1. Make a change to a submission and hit the back button. You should see the modal.
2. Make a change to a submission and hit the "Save and exit" button. You shouldn't see the modal.
3. Click a submission and hit the back button without making a change. You shouldn't see the modal.
See the steps in the README for how to log into the moderation panel.
-   ### Before
-   ### After
=> refactor: add check for unsaved changes to modEditSubmissionForm

renovate.json
Resolves #766 
Looking through the [json](https://docs.renovatebot.com/renovate-schema.json), [docs](https://docs.renovatebot.com/configuration-options/) and with some research the renovate bot settings were updated based on the requirements in the ticket.
1. Updates the lock-file and bumps the `package.json`
2. Only update type is `minor`
3. It also detects vulnerability alerts so runs to update on security patches
=> refactor: update bot to only run on minor and security updates

stores/moderationSubmissionsStore.ts
Resolves #802
Before there was not a specific function that was to just approve a facility. This has now been implemented in the store so it can be tested as well as used in the `ModEditSubmissionForm` in #718.
TBA > Before tests can be done we need to update our `vitest.config.ts` to be integrated with Nuxt to allow imports from the `nuxtApp` itself
This is being done in #821
=> feat: implement approve submission mutation in store

components/MainContentContainer.vue, components/ModEditSubmissionForm.vue, components/Modal.vue
Part of #770
This change adds a couple small improvements to the `Modal` component.
1. Moves the `v-show` to the component itself so we don't need to keep track of it everywhere it is used.
2. Emits `modal-closed` when the user hits the "X" button or clicks off screen. This will be useful for knowing when to reset the state of whatever called the modal (such as `approvingSubmissionFromTopBar`).
=> refactor: move state to modal component and add emit

nuxt.config.js, package.json, vitest.config.ts, yarn.lock
Resolves #821 
The `vitest.config.ts` was updated to use our nuxtApp as the base since our app runs through `Nuxt`. This will give our testing files access to our `#imports` and `#app` directories.
The tests are still passing
=> test: implement nuxt as vitest environment

components/ModEditSubmissionTopbar.vue, stores/moderationSubmissionsStore.ts
This PR moves the `rejectSubmission` API call from the top bar component to the `moderationSubmissionsStore`.
Tests will be added following #821
=> refactor: move rejectSubmission from component to store

.all-contributorsrc, README.md
We're unable to merge PRs created by all-contributors with `skipCI` set to `true` because of branch protections.
=> chore: set skip ci to false for all contributors config

components/ModHealthcareProfessionalSearchbar.vue, stores/healthcareProfessionalsStore.ts
Resolves #530 
**❗Changes Made Against Design ❗**
I have decided to only implement search a healthcare professional by id only, this is why;
At the moment we don't have a fuzzy search in the backend. This means that we need to search by exact name type like following: 
```
type LocalizedName {
firstName: String!
middleName: String
lastName: String!
locale: Locale!
}
```
So if you would make a request it should exactly match those fields. In my opinion I think it's better to just use the id for now. If we have a fuzzy search in the future we can implement searching by name.
- Fetch the healthcare professionals for the ModSearchHealthcareProfessional component
- Create graphQl query
- Create a moderationSearchHealthcareProfessionalStore
- Implement the UI for this part
=> feat: create logic for fetching healthcare professionals

cypress.config.ts, test/cypress/e2e/about.cy.ts, test/cypress/e2e/home.cy.ts, test/cypress/e2e/moderationDashboard.cy.ts, test/cypress/e2e/moderationEditFacility.cy.ts, test/cypress/e2e/submit.cy.ts
Resolves #866 
Before we were not maintaining good code quality by repeating the same timeout all over the cypress tests to make sure that our elements would be found. Cypress provides this setting in the configuration files as seen in the [documentation](https://docs.cypress.io/app/references/configuration#Timeouts). So we set this in the configuration files and removed the unnecessary code.
You can run the tests locally with `yarn cypress open`, but the tests in CI/CD reflect the changes that were done as it changed the global timeouts only
=> test: set defaultCommandTimeout to 10000ms for stability

components/ModEditFacilityOrProfessionalTopbar.vue, components/ModMainContent.vue, components/ModTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, stores/facilitiesStore.ts, stores/healthcareProfessionalsStore.ts, stores/moderationSubmissionsStore.ts, test/cypress/e2e/moderationEditFacility.cy.ts
Resolves #854 
Before there was no top bar that could be used in the screens in which we view and update or delete the facilities and healthcare professionals in our database. The respective Ids were moved into their respective stores for consistency in the code and separation of concerns with our stores. This also provides the clipboard functionality when a facility is selected
You can run the cypress tests by going to the branch and running
- `yarn cypress open`
From here you can choose the `moderationEditFacility.cy.ts` test run and they will pass and show the elements exist.
-   ### Before
N/A no topbar was implemented
-   ### After
https://github.com/user-attachments/assets/b45db4f1-1922-43e0-bfac-8f9d47afda0d
=> feat: implement mod top bar UI for hp and facility

components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue, stores/localeStore.ts
Resolves #891 
There was a bug that when the languages were formatted in an array there was no code, and the backend expects a code. So this has a function that fixes it so we display languages from code to text, and set the option value to the code itself. This allows us to send the correct information to the backend.
1. Fix the display to show text but set `option` value to the code
2. Fix the locales to be set initially to the values of spoken languages submitted
3. Change type button on the copy button to prevent default browser behavior
4. Add function to format a singular language code to simple text in order to display the healthcare professional spoken languages that are submitted
5. Update UI based on function
Currently while intercept and testing is being built. You need to …
=> fix: change locales to send code to backend

components/ModEditFacilitySection.vue, components/ModSubmissionListContainer.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, stores/facilitiesStore.ts, test/cypress/e2e/moderationEditFacility.cy.ts, test/fake_data/moderation_dashboard/fakeModFacilityData.json
Resolves #863 
Before we were not autofilling the form for the facility based on the selected Facility from the list. Now we can autofill the form when we go to this route.
Cypress tests were used to make sure the form was filled with our fake data. You can run by going to this branch and running:
`yarn cypress open` and navigate to the tests for `test/cypress/e2e/moderationEditFacility.cy.ts`
-   ### Before
-   ### After
https://github.com/user-attachments/assets/ed0300ec-c18d-4dae-94d4-e682f0ec2d86
=> feat: implement autofill to edit existing facility section

components/ModEditSubmissionForm.vue
Resolves #912
- The synthetic event was bubbling up causing the multiselect fields to be deselected. This made the frontend validation fail when the submission had been updated correctly.
Tests are currently being written #538
=> fix: remove bubbling from synthetic event

components/ModEditSubmissionForm.vue
Resolves #921 
The watch is changed to watch the singular value of selectedSubmissionId instead of the whole store. This then updates the form with the new values if this changes due to someone being sent to this form with a link instead of anything in the store changing. If it watches the whole store it can have unreliable ui updates that prevent the acceptance of a submission after an update to that submission
This bug was found in the creation and implementation of #538.
=> fix: change watch to selected submission Id to avoid unwanted UI updates

components/ModEditFacilityOrProfessionalTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, stores/facilitiesStore.ts
Resolves #916 
There was no way for an admin to delete a facility
Tests are being added in ticket #538 currently
We are discussing the best way to have a testing environment going forward.
=> feat: implement delete facility functionality to moderation panel

components/SearchBar.vue, stores/localeStore.ts
Resolves #900 
1. Swahili was removed from the options of what we have translated on our site. Even though we have a doctor that speaks Swahili. There is no translation of Swahili.
2. The search bar languages were changed to all the ones we include as `localeDisplayOptions` since even though we might not have the site translated yet within the language. We might have a doctor who speaks that language. As we do for Tagalog.
-   ### Before
-   ### After
=> fix(lang): update language dropdown options for search and i18n

components/SearchBar.vue, components/TopNav.vue, test/cypress/e2e/about.cy.ts, test/cypress/e2e/privacy.cy.ts, test/cypress/e2e/submit.cy.ts
Resolves #913 
1. Display the Search bar  on the index page only.
2. Make sure the Search bar is hidden on the about us page or add a doctor page.
N/A
-   ### Before
-   ### After
=> fix: implemented changes to display Search bar only on the index page

test/cypress/e2e/moderationDashboard.cy.ts
Resolves #540 
Before we were skipping a test that would click a button that copies the relevant `id` to a clipboard. I removed the skip due to our code having been updated to use lifecycle hooks to make sure the data is loaded before this button would be visible and then clicked. This test now passes.
You can see that in CI/CD the tests are passing. You could also checkout to this branch and run:
```
yarn dev
```
Followed by:
```
yarn cypress open
```
And going to the file `moderationDashboard.cy.ts` file within the cypress GUI and run the tests to see them pass. You can see that they pass if run over and over again.
=> fix: remove skip from clipboard test on the moderation panel

.github/workflows/lighthouse.yml
Resolves #143 
We had an issue to add lighthouse so we can work on finding ways to better our sites accessibility as an  NPO that focuses on healthcare. This action now runs on PRs, the main branch, and once a week on Wednesday in order for us to diagnose where we can improve our site going forward.
This pr uses the following [lighthouse action](https://github.com/treosh/lighthouse-ci-action/tree/v12/)
You can go to the workflow below and see the uploaded lighthouse scores for each of our paths. One example is the following link: https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1738807943395-80680.report.html
This link can be found in the screenshot below from the workflow when clicking on it.
-   ### After
=> feat: add lighthouse to workflows

.gitignore
Resolves #1006 
This PR adds the Cypress file to .gitignore to prevent test snapshots from being unintentionally committed when tests fail.
NA
=> fix: add cypress file to gitignore file

.github/workflows/cypress.yml, .gitignore, .yarnrc.yml, cypress.config.ts, eslint.config.js, package.json, test/cypress/e2e/moderationDashboard.cy.ts, test/cypress/e2e/moderationEditFacility.cy.ts, test/cypress/e2e/moderationEditHealthcareProfessional.cy.ts, test/cypress/e2e/moderationEditSubmissionForm.cy.ts, test/cypress/e2e/moderationEditSubmissionModal.cy.ts, test/cypress/support/commands.ts, test/cypress/support/e2e.ts, test/cypress/support/index.d.ts, test/cypress/tsconfig.json, test/cypress/utils.ts, test/fake_data/moderation_dashboard/fakeModHealthcareProfessionalData.json, yarn.lock
Resolves #797
Fixed Cypress linting
Added Yarn support for `.env.test` to securely manage environment
variables required for testing. The `.env.test` file includes:
- `AUTH0_DOMAIN`
- `AUTH0_USERNAME`
- `AUTH0_PASSWORD`
These variables are critical for the Auth0 login process. To ensure
security, only authorized individuals will have access to the
`.env.test` file, and it has been added to `.gitignore` to prevent
accidental commits of sensitive information.
Add Cypress cy.login() custom command
- Introduce an utils file with the following functions:
- `auth0Login`: Handles the Auth0 login routine
- `hasOperation`: Checks the request query for a specific operation
- `aliasQuery`: Adds an alias for an operation and stubs it
- Change file extensions to `.ts`
- Add Cypress plugin types to …
=> refactor: extract login from Cypress tests

package.json
Resolves #1011 
Before the script was missing ci which would cause the gui to open. For the test script we want it to all run in the console.
run the tests with
```
yarn test
```
and no GUI should appear for cypress
=> fix: add ci to e2e testing script

components/ModDashboardHealthProfessionalCard.vue, components/ModEditFacilityOrProfessionalTopbar.vue, components/ModEditHealthcareProfessionalSection.vue, components/ModEditSubmissionForm.vue, declarations.d.ts, nuxt.config.ts, package.json, stores/healthcareProfessionalsStore.ts, stores/localeStore.ts, yarn.lock
Resolves [#966](https://github.com/ourjapanlife/findadoc-web/issues/966)
- Update Nuxt to the latest version
- Add a declaration file containing a patch for the issue
The main issue was that Nuxt previously used the `@vue/runtime-core` namespace to augment the `vue` namespace. This caused conflicts with any package using `vue`.
As of Nuxt v3.13.0, they now use the `vue` namespace directly, which is the recommended approach. However, some packages, such as `@auth0/auth0-vue`, still rely on `@vue/runtime-core`, leading to compatibility issues.
Our solution involved creating a declaration file to patch this problem.
https://nuxt.com/blog/v3-13#vue-typescript-changes
=> feat: upgrade Nuxt to 3.15.2

components/ModEditHealthcareProfessionalSection.vue
Resolves #954 
added the loading component when opening a healthcare professional profile in moderation
loading is usually too fast, so changing network speed may allow you to view the loading component
-   ### After
https://github.com/user-attachments/assets/7214da0c-f3bc-4376-af49-3c3ccb95af34
=> feat: add loader to ModEdithealthcareProfessionalSection component

.github/pull_request_template.md
Resolves #[Issue number]
This adds a few additional checkboxes to the PR template to facilitate a smoother code review process.
-   ### Before
-   ### After
=> chore: add steps to PR template

.github/workflows/generate-gql-types.yml
✅ Resolves #1032 
Before this `cron` job was running but wasn't actually making a PR and exiting with an error code of 1 as seen in the before screenshot. Now it will run the script and if there are differences make a PR successfully as seen in #1034 automatically. After testing this was moved back to a `cron` job.
This uses this workflow action --> https://github.com/peter-evans/create-pull-request/tree/v5/
A PR will not be created if it isn't ahead of `main` as seen in the screenshot below.
-   ### Before
-   ### After
=> fix: update workflow to autogenerate PR with type differences

components/SearchResultsListItem.vue
✅ Resolves #1046 
`defineProps` was being unnecessarily imported since now it is a compiler macro. So it was removed from the import in the file where not necessary.
-   ### Before
-   ### After
=> fix: remove unnecessary `defineProps` import

components/LocaleSelector.vue, i18n.options.ts, i18n/index.ts, nuxt.config.ts
Resolves #889
Resolves #1022 
We no longer need the file './i18n.options.ts' to configure i18n.
The configuration is now handled directly in the Nuxt config file.
We are loading the last language used via cookies; therefore, we need to disable the language selector and display a loading indicator for the user until the loading process is complete.
The browser's language code uses "-", so we need to apply a small adjustment to align with our backend typing, which uses "_".
This PR initiates a discussion on refactoring/updating our backend. See it here: [GitBook](https://app.gitbook.com/o/Hmir5Cugknp7uJaXBpz1/s/znzEKbLPVwI181bff5yl/update-locale-enum-on-backend)
[Nuxt i18n Lazy-load translations](https://i18n.nuxtjs.org/docs/guide/lazy-load-translations)
[Nuxt Vue I18n …
=> feat: add lazy load to i18n

eslint.config.js, package.json, stores/facilitiesStore.ts, stores/healthcareProfessionalsStore.ts, stores/localeStore.ts, stores/locationsStore.ts, stores/moderationSubmissionsStore.ts, stores/searchResultsStore.ts, utils/stringUtils.ts, yarn.lock
✅ Resolves #982
We are now using the correct recommended TSESLint rules (`tseslint.configs.eslintRecommended.rules`).  
Previously, we were using the wrong plugin property: `tseslint.configs.recommended`. This includes not only the rules but the entire recommended plugin configuration.  
- #### Styling  
- `max-statements-per-line` turned off and removed `curly` ESLint rule.  
- #### `no-console`  
- Updated this rule to only affect `console.log`.  
- `console.warn`, `console.error` and `console.info` can still be used.  
- In the future, this rule should block all `console` commands once a logger is added.  
- #### `no-underscore-dangle`  
- Added ESLint ignore and renamed variables.  
- #### `no-shadow`  
- Renamed conflicting variables.  
- #### `consistent-return`  
- Removed the rule …
=> fix: ESLint config

.github/workflows/lint-locales-reaction-fix.yml, .github/workflows/lint-locales.yml, .gitignore, .husky/pre-push, i18n/checkLocaleKeys.js
Resolves #690
Before on push it would lint the locales and auto update them for you. Now you can run the script yourself locally. Or press a button on GitHub to run a webhook that runs the script for you that will commit and push for you. This makes it so if developers don't run `yarn prepare` that they can still have a button on GitHub when they create a PR. Also it keeps from autorunning and updating files when a feature is not done being worked on through every commit push if translations are added.
This was tested in a repository similar to ours since the workflow has to be in the main branch for it to work for comments
-   ### After
=> feat: implement button on GitHub to update locale files

.github/workflows/lint-locales-reaction-fix.yml, .github/workflows/lint-locales.yml
✅ Resolves #1055 
Before the dev to run the workflow to auto update and push missing keys to locale files had to make a new comment with 🌎 🌎 🌎 . Now it is just checking a box.
This had to be manually tested on a repository similar to this one since workflows with comments need to be on the main branch.
-   ### Before
-   ### After
=> feat: improve ux for devs triggering locale workflow

test/vitest/arrayUtils.spec.ts, utils/arrayUtils.ts
✅ Resolves #998
arraysAreEqual in utils/arraysUtils.ts can now sort and compare arrays that contain objects or arrays. It does this by turning the values into strings and then comparing them. Tests were also added in a new file test/vitest/arrayUtils.spec.ts that checks for primitive arrays as well as non-primitive.
"yarn test:pinia" runs the test
=> feat: refactor arraysAreEqual utility function to also handle non-primitive variables

components/ModDashboardHealthProfessionalCard.vue, components/ModEditFacilityOrProfessionalTopbar.vue, components/ModEditFacilitySection.vue, components/ModHealthcareProfessionalSearchbar.vue, components/ModTopbar.vue, stores/moderationScreenStore.ts
This PR does a couple small things:
1. It adds functions that will return `true` or `false` for the active moderation screen. This was just done so we can simplify the code a bit wherever we use conditionals such as `if (moderationScreenStore.activeScreen === ModerationScreen.EditFacility)` throughout the codebase. 
2. Updates a few variable names and types in the ModEditFacilityOrProfessionalTopbar so it's easier (hopefully) to understand their purpose.
3. Updates or removes a few comments.
=> refactor: update moderation store and ModEditFacilityOrProfessionalTopbar

cypress.config.ts
Before the global variable for auth env variables was being declared within the `cypress.config.ts`. Now it was removed since it caused CI/CD to fail and was unnecessary for tests
CI/CD passes now
-   ### Before
=> fix: remove global variable declaration of env for cypress

.gitattributes
- Added fix for windows `clrf` line endings. This should stop them from being generated and use `lf` instead
=> fix: fix clrf line endings on windows

components/SubmissionForm.vue
✅ Resolves #1076 
In the submission form, changed place-self-center to items-center to put the add doctor form content in the center of the page
pull this branch to your local machine, and try going to the add a doctor page. You should see the content in the center of the page for both firefox and chrome
-   ### Before
Chrome
Firefox
-   ### After
Chrome
Firefox
=> fix: add a doctor page is centered for both firefox and chrome

components/ModEditHealthcareProfessionalSection.vue, components/ModHealthcareProfessionalLeftNavbar.vue, components/ModLeftNavbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json, stores/moderationScreenStore.ts, utils/handleScroll.ts
✅ Resolves #968
Adds the ModHealthcareProfessionalLeftNavBar, add name also on i18n locales.
Mod Edit HealthcareProfessional has a left nav bar. Able to freely navigate by clicking.
The only little bug is when you click "Healthcare Professional Related Facilities". That section doesn't go at the top of the form, but i don't know if it's because the form is short or i have to modify utils/handleScroll
-   ### Before
-   ### After
=> feat: add leftNavBar for Healthcare Professional

components/ModCreateFacilityOrProfessionalTopbar.vue, components/ModCreateHealthcareProfessionalSection.vue, components/ModDashboardHealthProfessionalCard.vue, components/ModDashboardTopbar.vue, components/ModLeftNavbar.vue, components/ModMainContent.vue, components/ModSearchBar.vue, components/ModTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json, pages/moderation/create-healthcare-professional/index.vue, plugins/expose-pinia.client.ts, stores/healthcareProfessionalsStore.ts, stores/moderationScreenStore.ts, test/cypress/e2e/moderationCreateHealthcareProfessional.cy.ts, utils/graphql.ts
✅ Resolves #1044 #1080 
- Before there was no way to add a Healthcare professional from the moderation panel alone. Now the functionality is implemented. This is in case a moderator calls a hospital with a user submitted healthcare professional, they have the ability to add one right away. It is superfluous for them to submit their own through the main webpage when they are already in contact with the clinic or hospital and has the facility fresh in their mind.
- While looking through files we noticed a linter error in useLocalApi, so the type was updated to resolve it.
You can run tests as they were added for the flow of this component. Also as you can CI/CD is passing
-   ### Before
N/A
-   ### After
=> feat: add functionality for moderator to create healthcare professional

components/HamburgerMenu.vue, components/TopNav.vue, pages/moderation.vue
✅ Resolves #1128
- all instances of ``:to`` attributes on NuxtLink elements without dynamic urls have been replaced with ``to`` attributes with only one set of double quotes
- all links in the hamburger menu and topbar should work as expected
-   ### Before
N/A
-   ### After
N/A
=> refactor: all non-dynamic :to attributes replaced with to attributes

.env.sample, .github/workflows/cypress.yml, cypress.config.ts, nuxt.config.ts, package.json, server/api/auth-token.get.ts, server/api/test-environment.get.ts, stores/authStore.ts, test/cypress/support/commands.ts, test/cypress/utils.ts
✅ Resolves #570
Tests for auth are passing and use programmatic auth instead of the UI which is more consistent. We have server routes that protects attacks and changes the different types of environments.
One is for development,
One testing,
One production
Also scripts were made for testing to not need to run the server anymore for tests. The scripts will run the server based on each scenario and be separate from the manual testing.
To test the dev locally you can run `yarn test:e2e`
To test the dev locally headless you can run `yarn test:e2e:headless`
To test the prod build locally you can build it. Then run `yarn test:e2e:prod`
=> feat(test): implement testing for auth

.env.sample, .github/workflows/cypress.yml, cypress.config.ts, nuxt.config.ts, package.json, server/api/auth-token.get.ts, server/api/test-environment.get.ts, stores/authStore.ts, stores/facilitiesStore.ts, stores/healthcareProfessionalsStore.ts, stores/locationsStore.ts, stores/moderationSubmissionsStore.ts, stores/searchResultsStore.ts, stores/submissionStore.ts, test/cypress/support/commands.ts, test/cypress/utils.ts, typedefs/gqlTypes.ts, typedefs/serverResponse.ts, utils/graphql.ts
Resolves #574
Resolves #571 
**NOTE: Mod panel testing is not working right now. It's unrelated to the changes, it just never worked yet with real auth connected. Let's fix this in a separate issue/PR. I spent about 5 hours on it already.** 
- Added auth to every API request
- Built out auth token retrieval 
- Created Roles for admin, user, and moderator roles in auth0. 
- Created an auth0 workflow automation to add roles into the auth JWT token. 
- Created a set of scopes (too much to copy here)
- Assigned scopes to roles
- Assigned roles to current users
- Set up ROPG password flow for testing
- Changed to authenticate via API instead of manually clicking the login screen. This is because we were getting a consent popup that starts blocking our auth requests and will fail tests. 
- Had …
=> feat: add auth to API requests

stores/authStore.ts
✅ Resolves #1184 
The catch block had the wrong check making `loadSecret` not work properly for those in development. This led to developers not being able to access the mod dashboard locally
CI/CD still passes.
You can run the local server and make it to the mod dashboard manually in dev mode
=> fix: fix catch block in loadSecret function

components/ModMainContent.vue
The y scrolling was hidden which disallowed moderators from scrolling when submissions were over 25. This fixes that
-   ### After
https://github.com/user-attachments/assets/93235f46-6aa9-41d9-902c-9f0f9407354e
=> fix(style): make moderation dashboard scrollable

utils/closeOnOutsideClick.ts
The default browser action was causing weird side events for events when people were clicking if a modal was ever opened.
This prevents that from happening
-   ### Before
-   ### After
=> fix: add event default to prevent default action

components/ModEditSubmissionForm.vue, utils/closeOnOutsideClick.ts
Our `resetModalRefs` function that resets all the parts of the top bar and the modal was missing one of the values that needs to be reset to false. This has been fixed so the watch function that always watches when the dom changes does not auto update
Also the watch only looks at the necessary value of `updatingSubmissionFromTopBar`
=> fix: fix ref not being reset to false after submission update

components/ModEditSubmissionForm.vue
Put the correct validation for the url
=> fix: change which function validates google maps urls

components/ModCreateHealthcareProfessionalSection.vue, components/ModDashboardHealthProfessionalCard.vue, components/ModEditHealthcareProfessionalSection.vue, components/ModEditSubmissionForm.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json
✅ Resolves #1206 
Before we were displaying the spoken languages and not the name locale. This could lead to problems for moderators having not selected the correct locale for the typed name.
This makes it very interactive and shows exactly what is happening.
Also there is validation on the backend that makes sure that the locale of the name when Japanese only contains Japanese letters. This was causing a 500 error because we had no idea a wrong locale was chosen due to the previous ugly UI implementation by me.
-   ### Before
-   ### After
=> fix(style): display locale of name not spoken languages

components/ModDashboardLeftNavbar.vue
✅ Resolves #1238 
A conditional has been added to the createCountsForSubmissionListView which prevents it from running if the provided array of Submissions is empty. Optional chaining operators and nullish coalescing operators have also been added to where the sorted submission counts appear to prevent potential TypeScript errors or blank spaces if they are undefined.
-   ### Before
https://github.com/user-attachments/assets/fde7a1a6-c61c-4fc8-857b-4f6c3aafc0ae
-   ### After
https://github.com/user-attachments/assets/4551b327-445e-4f7e-9a98-8b6cb9685c64
=> fix: reduce method only runs when submissions are present

components/ModCreateFacilitySection.vue, components/ModCreateHealthcareProfessionalSection.vue, components/ModEditFacilitySection.vue, components/ModEditHealthcareProfessionalSection.vue, components/ModEditSubmissionForm.vue, components/ModSearchBar.vue
✅ Resolves #1248 
Previously, clicking on the input field in the `ModSearchBar` component did not show any search suggestions unless the user started typing.  
Now, default suggestions are displayed as soon as the input is focused, improving discoverability and UX.
1. Navigate to a page using the `ModSearchBar`.
2. Click on the search input field.
3. Verify that a list of suggestions appears even before typing.
4. Try typing to see the suggestions filter in real-time.
5. Blur and focus the input again to confirm consistent behavior.
https://github.com/user-attachments/assets/2454684f-db32-4d76-8989-7e4c7515bf5e
=> feat: show search suggestions on input focus in ModSearchBar component

components/SearchResultDetails.vue
✅ Resolves #1245 
- Added an anchor tag around the address to the Google Maps link in the `resultsStore` which opens in a new tab
- Added styling to the link (inspired by #1250)
Try clicking the link.
**Currently the link won't work due to the `preventDefault` in closeOnOutsideClick.ts which is removed in #1249**
-   ### Before
-   ### After
=> feat: address in modal opens link in new tab; link styling

assets/css/tailwind.css, assets/icons/hamburger-menu.svg, components/HamburgerMenu.vue, utils/stringUtils.ts
✅ Resolves #1041 
Added 'high contrast' and 'color blind: daltonism (red green colorblindness)' themes to theme selector. 
Theme selector now displays theme title upon user selection.
1. Reduce size of viewing window to 'less than 1080p' to enable 'hamburger' menu. 
2. Click 'humburger' menu to display settings and theme selector
3. Select theme of choice
-   ### Before
-   ### After
=> fix: add accessible themes

components/Footer.vue, components/HamburgerMenu.vue, components/LoginForm.vue, components/ModCreateFacilityOrProfessionalTopbar.vue, components/ModCreateFacilitySection.vue, components/ModCreateHealthcareProfessionalSection.vue, components/ModDashboardHealthProfessionalCard.vue, components/ModDashboardLeftNavbar.vue, components/ModDashboardTopbar.vue, components/ModEditFacilityOrProfessionalTopbar.vue, components/ModEditFacilitySection.vue, components/ModEditHealthcareProfessionalSection.vue, components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue, components/ModHealthcareProfessionalLeftNavbar.vue, components/ModHealthcareProfessionalSearchbar.vue, components/ModSubmissionLeftNavbar.vue, components/ModSubmissionListContainer.vue, components/SearchBar.vue, components/SearchResultDetails.vue, components/SearchResultsList.vue, components/SubmissionCompleted.vue, components/SubmissionForm.vue, components/TopNav.vue, pages/about.vue, pages/moderation.vue, pages/privacypolicy.vue
✅ Resolves #1252 
Declared the $t property in global.d.ts to fix the type error shown in components
Reason: Vue and TypeScript don't recognize the `$t` property by default, which causes a type error `'__VLS_ctx.$t' is of type 'unknown'` .  
I used `Composer['t']` because it's a translation function provided by Vue I18n. By declaring `$t` as `Composer['t']`, every `$t` property used in Vue components will be recognized by TypeScript as the translation function. 
-   ### Before
-   ### After
=> fix: declare $t to resolve incorrect TypeScript error message for translatable strings

stores/facilitiesStore.ts
✅ Resolves #1186 
This PR updates the logic inside the `updateFacility()` function to unconditionally clear `facilitySectionFields.healthProfessionalsRelations` after a successful facility update.
By resetting the array once the update is confirmed, the code avoids potential race conditions and ensures a clean state for the next user interaction.
=> fix: avoid race condition `facilitiesStore.ts`

components/MainContentContainer.vue, components/Modal.vue
Remove pink background on main page and use our own utility for screen orientation
Mod panel
Main page. Path will need to be updated in @ermish ui redesign if he changes the page to `/search`
=> fix(style): change styling for modal on main page

components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
✅ Resolves #1274 
Before, if you would delete a facility, the `UnsavedChanges` modal would appear after the `DeleteConfirmation` modal. Which makes no sense, because the facility is already deleted.
Now, 
1. `deleteFacilityOrHealthcareProfessional()` runs, and you confirm your choice on the `DeleteConfirmation` modal
2. The ref `originalFacilityRefsValue` turns to `undefined`-- all memory of the now deleted facility gets wiped
3. `facilityHasUnsavedChanges()` runs, but there is nothing to compare with anymore, resulting in the `UnsavedChanges` modal being skipped 
4. You return back to the facility overview page
=> fix: prevent `UnsavedChanges` modal from appearing when deleting a facility

components/SearchResultDetails.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json, stores/searchResultsStore.ts
✅ Resolves #1360 
Currently, additional info for patients is shown in mod panel, but not to the user yet. This PR shows it in the search result details in the modal on the main page
Pull this branch, add some additional info to a hp in the mod panel locally, and see if you can see that same additional info show up for that hp in the modal details 
-   ### Before
-   ### After
=> feat: show additional info in SearchResultDetails

i18n/locales/en.json
✅ Resolves 
Somehow, en.json was missing searchResultsDetails.lastUpdate. The other json files still have this key. I added it back into en.json
-   ### Before
-   ### After
=> fix: add missing last update locale in en.json

components/moderation-panel/ModCreateHealthcareProfessionalSection.vue, components/moderation-panel/ModEditHealthcareProfessionalSection.vue
Before it would not allow you to edit even if you were updating the current locale. This is now fixed as we track it and make sure you can update the current one
=> fix: fix update name to allow for current name locale

components/moderation-panel/ModEditSubmissionForm.vue
This only validates the names if there aren't existing healthcare professionals selected for the facility
=> fix: remove validation for having English name when selected healthcare professional

components/SubmissionForm.vue
Before two languages were optional. This seems unnecessary. To pass all medical exams and in all practical purposes, healthcare professionals must speak Japanese.
=> refactor: change submission secondary language to optional

components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue, components/moderation-panel/ModCreateHealthcareProfessionalSection.vue, stores/healthcareProfessionalsStore.ts
There were no additional notes for creating a healthcare professional. Also the validation was failing do to using `Object.values` This makes our choice of validation more readable and distinct as to what fields are necessary.
=> fix: add additional notes to create healthcare with validation fix

test/cypress/e2e/moderationCreateFacility.cy.ts, test/cypress/e2e/moderationEditFacility.cy.ts, utils/formValidations.ts, utils/stringUtils.ts
This updates it based on what we have found is common within names of clinics and hospitals while moderation
Can test it manually
-   ### Before
ONLY JAPANESE CHARACTERS. NOTHING ELSE!
-   ### After
MORE OPTIONS DUE TO OUR CASE
1. Valid
2. Invalid
=> refactor: update validation for facilityName English

i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json, stores/facilitiesStore.ts
The `},` is missing between `modSubmissionListContainer` and `errorPage`, which results in the error seen on the screenshot below.
Fixed a typo where the `modSubmissionListContainer` locale section in every language, except English, was missing a closing brace and comma, which resulted in an error every time you would interact with one of the locales.
=> fix: added missing `},` for `modSubmissionListContainer` locale section

typedefs/gqlTypes.ts
Adds mongolian that was added to the schema on the backend by generating the types
=> chore: generate types

components/moderation-panel/ModEditSubmissionForm.vue
remove DataSubmission reference from `initializeSubmissionFormValues` in modeditSubmission
=> fix: mod edit submission form autofill

components/HamburgerMenu.vue
✅ Resolves #1493 
There's a bug where the mobile hamburger menu is closing even when clicking within the hamburger menu. With the closeOnOutsideClick composable directive, this is not supposed to happen. 
It is likely due to the Teleport tag being used in the Hamburger menu to transition to the inner div menu. 
To solve this issue, I used `@click.stop` within that inner div. This seems to have fixed the issue
Try pulling the branch and clicking within the menu. It should not close. It also should close when clicked outside or clicking the X in the top right corner
It should also be able to still go to other links (it was able to for me)
-   ### Before
-   ### After
=> fix: hamburger closes on inside click

components/SearchResultsList.vue
This integrates a click event to be tracked on umami for when a search result item is clicked. It is simple for now as a test and we can add more in depth click events or other desired ones later
This follows the documentation from [umami track events](https://umami.is/docs/track-events)
=> feat: enable tracking of clicked healthcare professional item with umami
