CODE_OF_CONDUCT.md, CONTRIBUTING.md
Adds the Code of Conduct and Contributor guidelines.
=> Add Code of Conduct and Contributing Guidelines

components/TopNav.vue
Adds a donation button to the top nav.
=> Add Donation Button

CONTRIBUTING.md, README.md
1. Removes links to resources we no longer use
2. Updates the Slack channel information
3. Updates the technologies we use
=> docs: update CONTRIBUTING.md

README.md
Fixes a broken link to the site in the README.
=> fix: link to site in README

CONTRIBUTING.md
This resolves our challenging #70 issue. 😸
=> docs: Updated the contributor guide to be beginner friendly

README.md
Adds a link to the `CODE_OF_CONDUCT.md` file to the README.md
=> docs: add the CODE OF CONDUCT to the README

assets/images/logo-32-px-color.svg, components/TopNav.vue
Resolves #50 & #51 
- Add logo-32-px-color.svg to images directory
- Create "home" link on navbar; incorporate logo
n/a
=> Create logo; add to Home link in navbar

components/TopNav.vue
Resolves #76 
Removed Buy Me a Coffee button
P.S. (fixed my merge conflict from before)
=> remove BuyMeACoffee btn

components/LocaleSelector.vue, components/TopNav.vue
Resolves #58
Added a dropdown menu to select a language (English & Japaneses)
=> add language dropdown

plugins/vue-gtag.client.js, tsconfig.json
Resolves #80 
- Fixed ESM import 
- Run `yarn dev` and confirm no errors are showing up
=> bug: fixed yarn dev error

CONTRIBUTING.md
Just link to the wiki page I made for discoverability
=> Guide beginners to resources for learning OSS and Git/GitHub

.github/workflows/lint.yml, package.json
Resolves #107
Added the stylelint lint (made the output verbose)
Run the Action
=> Add styelint workflow #107

.husky/commit-msg, commitlint.config.js
Resolves #116 
- removed commit lint
- ensure build still runs
- you can commit code without errors
=> removing commitlint

app.vue, components/WelcomeSection.vue, nuxt.config.js
Resolves #120 
- Root problem was two parts: 
- 1) Nuxt 3 config changed for postcss and tailwind integration. 
- 2) A `<container>` element added in app.vue wasn't rendering properly.
- run `yarn dev` and validate the site is rendering correctly
=> BUG: fix tailwind 

.eslintrc.js, app.vue, assets/images/hamburgerListIcon.svg, assets/images/profileIcon.svg, components/LeftNavbar.vue, components/SearchResult.vue, components/SearchResultsList.vue, components/WelcomeSection.vue, nuxt.config.js, pages/index.vue, tailwind.config.js, tsconfig.json
Resolves #37
This PR includes new components for the Left Navbar, Search Results List, and the Search Result. 
- Open up the app and view the new left nabber with results listed
=> feat: Created Left navbar, search results list, and search result components

components/MapContainer.vue, components/SearchBar.vue, cypress/e2e/home.cy.ts, pages/index.vue
Resolves #146 
this makes it easier to visualize the upcoming welcome banner changes  
- a map shows!
=> feat: prepare map work and temp map img

CONTRIBUTING.md, README.md
Fixes #158 
- Add placeholder for All Contributors Bot (following [these instructions](https://allcontributors.org/docs/en/bot/installation))
🤔 Let's see how soon the bot starts working 🤖 
I think we might have to merge to main to see if it works.
=> Configure all contributors

.all-contributorsrc, README.md, package.json, yarn.lock
Resolves #163 
- installed All contributors CLI
- actually generated the README content correctly
Feel free to add your own contributions by running `yarn install` and then `yarn all-contributors add [your-username] review`
(Ok to modify the branch while testing, you earned it. ⭐ )
=> 163 install all contributors cli and fix the README

.editorconfig
Resolves #162 
- add line ending preference
- recommend utf-8
Try it in your editor, you will need a supported editor or plugin: https://editorconfig.org/
=> improve editorconfig

.gitattributes
Resolves #172
- add gitattributes based off of https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes
1. Make a new branch off of this one.
2.  Try editing some files and committing.
3.  Ensure git operates smoothly
=> add web gitattributes

package.json, typesgeneratorconfig.ts, yarn.lock
Resolves #203 
- build shouldn't fail.
=> Added typescript gql generator

README.md
=> updated documentation with type generating

components/LocaleSelector.vue, components/SearchBar.vue, components/SearchResultsList.vue, components/TopNav.vue, i18n/index.ts, i18n/locales/en.json, i18n/locales/ja.json, nuxt.config.js, package.json, yarn.lock
Resolves #60 
Wire up the locale selector to nuxt/i18n
Note: this doesn't necessarily work with #59... it seems the preferred way is to use a cookie ([read more here](https://i18n.nuxtjs.org/browser-language-detection)). Can decide how to fix in a future issue
- Edit the locale selector and ensure the language changes
=> 60 locale wire up

.eslintrc.js, components/Footer.vue, components/MapContainer.vue, components/SearchBar.vue, components/TopNav.vue, cypress/e2e/home.cy.ts
Resolves #168 
- Added all testing queries using cypress
- Added data-testid to multiple elements in search bar and footer
- "changed linebreak-style": 0 in eslintrc under rules in order to tackle the linting issue
=> Cypress testing tch4lla

assets/css/tailwind.css
1. Used `yarn lint --fix` to lint the files currently on main.
1. Run `yarn lint --fix` and confirm that there aren't any additional changes.
=> chore: lint tailwind.css

.gitignore, components/LeftNavbar.vue, components/MapContainer.vue, components/SearchBar.vue, components/SearchResultDetails.vue, components/SearchResultsList.vue, pages/index.vue, stores/locationStore.ts, stores/searchResultsStore.ts, test/mockData/facilityMockData.json, tsconfig.json
Resolves #[Issue number]
Search filters and search result list now working.
=> making it demo ready!

components/SearchResultsList.vue, i18n/locales/en.json, i18n/locales/ja.json
=> Change Filter raw text to i18n string

components/SearchResultDetails.vue
Refactor `a href` so it can read the `website` variable that was causing an error in the build.
=> fix: refactor website var to fix build

components/Footer.vue, components/MapContainer.vue, i18n/locales/en.json, nuxt.config.js
1. Puts footer text into localizable strings
2. Updates the runtime config variables
=> chore: update localization and credentials

netlify.toml
Update netlify.toml to include headers
=> add headers to netlify.toml

netlify.toml
=> add redirect to toml

pages/_headers
=> create headers file for CORs

stores/searchResultsStore.ts
Previously, the refetch handles were being defined but never used. This checks if they are defined and uses them instead of the normal search functions if so.
=> use the refetch handles if defined

stores/searchResultsStore.ts
Fix the query to include the 2nd line of the address for the facility.
=> Fix address line in ja_JP

components/MapContainer.vue, components/SearchResultsList.vue, stores/searchResultsStore.ts, typedefs/gqlTypes.ts
Fixed queries and data fetching ui bugs
=> Fixed queries and data fetching ui bugs

stores/searchResultsStore.ts
fixed cached queries not re-running
=> fixed cached queries not re-running

pages/terms.vue
=> add terms and conditions

typesgeneratorconfig.ts
Resolves #330 
fixing prod url
=> fixed url for generator

components/Footer.vue, tailwind.config.js
* Update footer to be responsive
Added media query for screens up to 640px. Footer will align itself into a single column with each section in its own row
* Fix yarn errors
changed the spacing to 2 instead of the default 4.
* Update style syntax to tailwind css syntax
Resolves #[Issue number]
=> Tch4lla/responsive footer (#338)

components/HamburgerComponent.vue, components/MainContentContainer.vue, components/TopNav.vue, nuxt.config.js, package.json, pages/index.vue, yarn.lock
This PR is part of a 🥞
1. https://github.com/ourjapanlife/findadoc-web/pull/352 
2. https://github.com/ourjapanlife/findadoc-web/pull/351 👈🏼 You are here
3. https://github.com/ourjapanlife/findadoc-web/pull/353
Adds the [nuxt-viewport package](https://nuxt.com/modules/nuxt-viewport). This will make it significantly easier to detect and adjust the layout of the site based on the user's screen size.
=> feat: add nuxt-viewport for breakpoints

stores/locationsStore.ts, stores/menuStore.ts, stores/searchResultsStore.ts, stores/submissionStore.ts
🧹 Doing a bit of cleaning up.  ✨ 
I noticed that the console is overrun with data that we're already rendering in the UI. I removed any that weren't logging errors. Eventually, we'd like to use a service like [Datadog](https://www.datadoghq.com/) so we can remove those as well.
I also removed the alerts, because not only are they bad for the user experience, but they could also cause our site to be penalized by Google if they pop up too often.
=> chore: remove console logs and alerts

components/SearchBar.vue
Resolves #427 
I added a function that would make a lookup of location with key value pairs in order to make it so we can render based on location and how many doctors in that location. That is then used to render and search for doctors based on the value.
None at the moment
-   ### Before
-   ### After
=> fix: remove duplicate locations

.github/ISSUE_TEMPLATE/default.md
Updating the template for new issues to help provide devs with more context and details.
=> Update default template for Issues

components/ModSubmissionListContainer.vue, components/ModSubmissionListItemComponent.vue
Resolves #452 
We created:
-  a component that displays the fake data in the ModSubmissionListContainer.
- an on-click event to take you to the relevant submission form. 
- In future we need to create a ticket to set up the logic for connecting specific data entries to specific submission forms.  
-   ### Before
-   ### After
=> feat: implement list item component with partial functionality

pages/moderation.vue
This change will uncomment the routes that were unintentionally commented out in #506.
=> chore: uncomment routes in moderation.vue

components/ModDashboardLeftNavbar.vue, cypress/e2e/moderationDashboard.cy.ts, i18n/locales/en.json, i18n/locales/ja.json
Resolves https://github.com/ourjapanlife/findadoc-web/issues/514
🔧 What changed
The ModDashboardLeftNav was being dynamically generated. But now it is all static with the same logic as before.
📸 Screenshots
Nothing Changed in terms of design. Before and after are the same.
=>  refactor: change dynamic code to static

components/ModHealthcareProfessionalSearchbar.vue, components/ModSubmissionsEditFormFacility.vue, cypress/e2e/moderationDashboard.cy.ts, i18n/locales/en.json, i18n/locales/ja.json
Resolves #529 
- Create healthcare professional search bar component for the facility edit form
- Applied the UI for the search bar
- Removed some small bugs that I notice in the form component
Run the cypress tests.
Fetch the healthcare professionals for the facility
=> Create healthcare professional search component

components/ModSubmissionListContainer.vue, cypress/e2e/moderationDashboard.cy.ts, i18n/locales/en.json, i18n/locales/ja.json, stores/moderationScreenStore.ts, stores/moderationSubmissionsStore.ts
Resolves #510 #537
1. The store now fetches data from the database.
2.  The data that was fetched is displayed in the Moderation Dashboard
1.  Run your local backend server and db emulator.
2.  Run `yarn dev:localserver`
3. Go to the route `/moderation`
-   ### Before
-
-   ### After
=> feat: add query to get submissions

app.vue, components/MapContainer.vue, components/MemberComponent.vue, components/ModDashboardLeftNavbar.vue, components/ModEditSubmissionTopbar.vue, components/ModHealthcareProfessionalSearchbar.vue, components/ModInputField.vue, components/ModSubmissionListContainer.vue, components/SearchBar.vue, components/SearchResultDetails.vue, components/SubmissionCompleted.vue, components/SubmissionForm.vue, nuxt.config.js, package.json, tsconfig.json
- Adding support for nuxt variables and plugins into typescript compiler.
- We should not have any more $t() errors!
- import from '#app' should work now. We can get vueApp variable
- app should still work!
- you shouldn't see any more $t() errors
=> fix: fix typescript errors in the app

components/ModHealthcareProfessionalSearchbar.vue
Is Part of #546 
Changed the fonts to `font-sans`
=> Change fonts in  searchbar

i18n/index.ts, i18n/locales/pt.json, stores/localeStore.ts
- Added the portuguese json file with all text in portuguese.
- Add the portuguese json file in the index.ts file to export it.
- Added the portuguese option in the mvpLocaleDisplayOptions type, in the localeStore.
- Changed from "Portuguese" to "Português" and switched from "Brazil" to "Brasil" in the localeDisplayOptions type in the store.
Access the application, change the language settings to "Português" and note the text changes to words in portuguese.
-   ### Before
-   ### After
=> Added the portuguese json file and add the option

README.md
Resolves #594
Production commands were updated.
Input production commands.
-   ### Before
-   ### After
=> Update README.md to reflect new commands for production.

components/ModSubmissionListContainer.vue
Resolves #600 
I add a styling class to the outer div element in the ModSubmissionListContainer.
Start the app.
-   ### Before
-   ### After
=> Add the correct style class to div element in ModSubmissionListContainer

.github/workflows/cypress.yml
Resolves #577 
added script to upload screenshot if the PR fails.
Not sure how to test this, except trying it.
If you have any recommendations, please advise.
-   ### Before
-   ### After
=> feat: add cypress screenshot code to yaml file

assets/css/tailwind.css, components/ModEditSubmissionTopbar.vue, components/ModHealthcareProfessionalSearchbar.vue, components/ModInputField.vue, components/ModSubmissionListContainer.vue, components/ModSubmissionsEditFormFacility.vue, components/SearchResultDetails.vue, components/SubmissionCompleted.vue, components/SubmissionForm.vue, pages/index.vue, pages/privacypolicy.vue, pages/terms.vue, tailwind.config.js
Resolves #546 
- Before some styling classes contained hard coded colors, I have changed them to our set class colors
- Before some styling classes contained px values I have changed them to the Tailwind standards
=> FIX: Change styling values using our Tailwind classes

package.json, plugins/vue-toastification-plugin.ts, yarn.lock
Resolves #658 
https://github.com/Maronato/vue-toastification#features
I added a library that allows us to use customizable toast notifications. The linked ticket shows the research I did and reasoning I implemented a package instead of using our own but I will copy that down here.
- Features of vue-toastification
- Compatible with Vue 3
- Written in TypeScript, with type support
- Inbuilt swipe-to-close interaction
- Ability to remove the toast programmatically
- A window focus() method pause feature
- Right-to-left and left-to-right text support
- You can [find a full list of features](https://github.com/Maronato/vue-toastification#features) on GitHub.
- Support for Vue 3
- Available as a plugin or via the [Composition API](https://blog.logrocket.com/reactivity-vue-3-composition-api-ref- …
=> feat: implement toast plugin for app

components/ModSubmissionListContainer.vue
Resolves #703 
Fixed bug by changing facility to healthcare professional name. 
-   ### Before
-   ### After
=> Fix: professional name now displays on mod dashboard.

components/ModSubmissionListContainer.vue
Resolves #714 
I have replace the `<nuxt-link>` with `<NuxtLink>` since this is how the documentation recommend it: https://nuxt.com/docs/api/components/nuxt-link
=> refactor: replace nuxt-link with NuxtLink

components/ModDashboardLeftNavbar.vue, components/ModDashboardTopbar.vue, components/ModTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, stores/moderationSubmissionsStore.ts
Resolves #735 
Before we didn't even have a topbar UI/UX. This does not have any search functionality as of now. Since we need to decide how we want to do this in the future.
Manually test it by making sure it updates as expected.
- run the backend with
1. `npm run dev:startlocaldb`
2. `npm run dev`
- go to the frontend and run
1. yarn dev:localserver
2.  go to the moderation panel and switch the dashboard views
-   ### Before
-   ### After
=> feat: implement dashboard topbar

components/ModEditSubmissionForm.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json
Resolves #700 
A modal was added that only triggers on use of the back button in the browser.
No tests were added. 
-   ### Before
It didn't exist before. 
-   ### After
https://github.com/user-attachments/assets/62b0dcf1-436b-45ec-a8b5-77c3f0afb8f5
=> feat: create back button submission form modal 

components/ModEditSubmissionForm.vue, eslint.config.js, i18n/checkLocaleKeys.js, utils/handleScroll.ts, utils/multiSelectWithoutKeyboard.ts
Resolves #[Issue number]
Set max length for comments to 130 characters in our Eslint config file under the styling rules.
NA
NA
=> chore: set max length for comments in code styling rules

stores/facilitiesStore.ts
Resolves #828 
A mutation was added to the `facilitiesStore.ts` to update existing facilities that can be used in the Moderation Panel to update an existing facility.
Tests for this will be added in #803 as proper research and implementation of mocking our `graphQL` function through Nuxt needs to be implemented after research
=> feat: add mutation to update existing facility

stores/healthcareProfessionalsStore.ts
Resolves #830 
This adds a mutation to the store to update Healthcare Professionals.
Tests will be added in #804 when proper research of mocking `graphQL` request have been researched and implemented
=> feat: add mutation to update healthcare professional

components/ModEditSubmissionForm.vue, components/ModEditSubmissionTopbar.vue, components/SubmissionCompleted.vue, components/SubmissionForm.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, pages/submit.vue, stores/moderationSubmissionsStore.ts, stores/submissionStore.ts, test/cypress/e2e/submit.cy.ts, typedefs/serverResponse.ts, utils/graphql.ts, utils/handleServerErrorMessaging.ts
Resolves #873
- the `ServerResponse` type was changed to match what is delivered from the `resolvers` from the backend based on the built in graphQLError we must covert our backend to before messaging to the frontend.
- Error toasts and success toasts are displayed to the user on the frontend depending on the submission status
- The api call now uses the built in retry and returns the response where we have access to the submission and to the errors
- Updated `SubmissionForm.vue` to use lifecycle hooks in order to render the form once the refs are loaded within the component
- Component specific refs for the submission were moved to the component and our of the store
- The thank you component has a button to submit another doctor and the forms are conditionally rendered in order to …
=> fix: improve submission form ui and ux

components/ModDashboardHealthProfessionalCard.vue, components/ModEditFacilitySection.vue, components/ModEditHealthcareProfessionalSection.vue, components/ModSubmissionListContainer.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, stores/healthcareProfessionalsStore.ts, utils/multiSelectWithoutKeyboard.ts
Resolves #864 
The selected healthcare professional's information is now autofilled. 
If the professional has name info in another locale that also autofills when the locale is selected. 
-   ### Before
-   ### After
https://github.com/user-attachments/assets/27b7b571-da7e-4e78-9eeb-22fb18eeb82a
=> feat: autofill the healthcare professional info in mod

.github/workflows/lint-locales-reaction-fix.yml
=> feat: register workflow for testing locales

.github/workflows/lint-locales-reaction-fix.yml
=> feat: update workflow

.github/workflows/lint-locales-reaction-fix.yml, .github/workflows/lint-locales.yml
=> fix: update workflow

.github/workflows/lint-locales-reaction-fix.yml, .github/workflows/lint-locales.yml
=> chore: update workflow run

.github/workflows/lint-locales-reaction-fix.yml
=> chore: update workflow action

.env.sample
Resolves #1020 
We didn't have a `.env.sample` file for developers to follow in order to add variables for running the moderation panel tests. This was added with the relevant variables and instructions for the developers.
=> feat: add .env.sample with necessary variables

components/ModMainContent.vue
✅ Resolves #[1080]
The multiple if statements in ModMainContent have been changed to a single switch 
-   ### Before
N/A
-   ### After
N/A
=> fix: if statements changed to switch for mod active screen

components/ModDashboardHealthProfessionalCard.vue
✅ Resolves #1106
When changing the past way to check moderation screen check this got removed which got rid of the functionality for a moderator to finish
It is visible now
-   ### Before
- 
-   ### After
=> fix: add the trash can icon back for edit facility

components/ModEditFacilityOrProfessionalTopbar.vue, stores/healthcareProfessionalsStore.ts, test/cypress/e2e/moderationEditHealthcareProfessional.cy.ts
✅ Resolves #1103
**Status: Work in Progress**
- buttons when editing a healthcare professional are disabled until changes are made
- selectedHealthcareProfessionalData added to healthcareProfessionalsStore
Tests were added in moderationEditHealthcareProfessional.cy.ts
-   ### Before
N/A
-   ### After
N/A
=> fix: mod edit healthcare professional buttons not disabled

components/MapContainer.vue
There was a JS error from google maps. It's because the vue3-google-maps component renders the map before the component is ready and throws an error.
- Verify you don't see that error anymore
-   ### Before
-   ### After
No error!
=> fix: fixed google maps js error

.github/workflows/cypress.yml, nuxt.config.ts, package.json, server/api/auth-token.get.ts, stores/authStore.ts
✅ Resolves #1173
Scripts were updated for ci since it needs to run off the server to get the env variable for cypress testing. This will be different than prod but as close to a simulation as possible since we do not use server side routes currently in our public site
Make sure to add `NUXT_CYPRESS_TESTING=true` to your `.env`
run the following
```
yarn ci:build
yarn ci:start
yarn test:e2e:ci
```
=> feat(test): implement tests for ci

package.json
✅ Resolves #1192 
The script for running the whole testing suite was outdated. It has been updated with the new command.
Run your tests with `yarn:test` and by following the documentation
https://documentation.findadoc.jp/development/start-coding/testing/running-tests
=> chore: update script for test to new e2e headless command

test/vitest/healthcareProfessionalsStore.spec.ts
✅ Resolves #804 
test file for HealthcareProfessionalStore has been added
``yarn test:pinia``
-   ### Before
N/A
-   ### After
N/A
=> feat(test): add tests for healthcareProfessionalsStore

stores/facilitiesStore.ts
✅ Resolves #1221 
There is now a function to reset the facility sections in case we need to send back no data for just a new healthcare professional or when we navigate between screens
=> feat: implement function to reset facility sections

utils/formValidations.ts
✅ Resolves #1218 
A function was added to validate if name locales that are written by moderators check the correct the Locale has the correct characters
=> feat: add form validation for name locales

stores/healthcareProfessionalsStore.ts
✅ Resolves #1220 
A reset was made for the `healthcareProfessionalSection` for when necessary moving between different sections
=> feat: implement function to reset healthcare professional section

components/ModCreateFacilityOrProfessionalTopbar.vue, components/ModCreateFacilitySection.vue, components/ModDashboardHealthProfessionalCard.vue, components/ModDashboardTopbar.vue, components/ModHealthcareProfessionalSearchbar.vue, components/ModLeftNavbar.vue, components/ModMainContent.vue, components/ModTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json, pages/moderation/create-facility/index.vue, stores/facilitiesStore.ts, stores/moderationScreenStore.ts, test/cypress/e2e/moderationCreateFacility.cy.ts
✅ Resolves #1043 
- On the left navbar for the moderation panel dashboard, choose "Facilities" in the dropdown menu. Then there is a button on the topbar to add a new facility.
- When clicking on the button, you will be directed to a blank facility form without an ID (ID section is also removed from the topbar).
- The top navbar also changes when clicking on the "Add Facility" button, and you will have the choice between "Create" (creating the new facility entry if the requirements are met) and "Exit" (going back to /moderation without saving).
- NameEn, NameJp, Latitude/Longitude cannot be left empty as of now. Everything else the form will accept. Input forms are the same as for `modEditFacilitySection.vue`. You will not be able to save the entry if the requirements are not met, and you …
=> feat: add functionality for moderator to create a facility

components/SearchResultDetails.vue, utils/closeOnOutsideClick.ts
✅ Resolves #1244 
- A `preventDefault` in closeOnOutsideClick.ts ha been removed; this is what was preventing the doctor link to work correctly.
- Attributes which allow the link to open in a new tab, provide a bit of security, and styling so it looks like a clickable link.
Click on the links in the modal.
-   ### Before
-   ### After
=> fix: doctor website link functionality

assets/icons/loading.svg
- updated our loader SVG to match new brand colors!
=> feat: updating loaded to match new branding theme

stores/authStore.ts, stores/specialtiesStore.ts, test/cypress/e2e/home.cy.ts, typedefs/gqlTypes.ts
Running `yarn generate` had some unchecked in results. Let's fix this!
=> feat: ran yarn generate

components/SubmissionForm.vue, components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue, components/moderation-panel/ModCreateHealthcareProfessionalSection.vue, components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue, components/moderation-panel/ModEditFacilitySection.vue, components/moderation-panel/ModEditHealthcareProfessionalSection.vue, components/moderation-panel/ModEditSubmissionForm.vue
✅ Resolves #1278 
Toast variables were updated to const from let. 
Removed references from onMounted and onBeforeMount. 
Cleaned up unnecessary imports. 
Not applicable. All existing functionality should remain unchanged. 
-   ### Before
-   ### After
=> refactor: update toast variables

stores/authStore.ts
Working towards users having their own settings
=> feat: add user metadata

components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue, i18n/locales/cn.json, i18n/locales/de.json, i18n/locales/en.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/ja.json, i18n/locales/pt.json, i18n/locales/ru.json, i18n/locales/tl.json, i18n/locales/vi.json
This locale was removed by accident during clean locales. That needs to be inspected still since it uses variables
So we added the locale back and centered the button
=> chore: add missing deletion translation 

components/moderation-panel/ModListContainerItem.vue
Changed the color to yellow
-   ### Before
-   ### After
=> feat(style): change styling of tag for approved

typedefs/gqlTypes.ts
✅ Resolves #1457 
Add OD to `healthcareProfessional` degree options.
1. Create/Update Health Care Professional with degree "OD" 
2. Confirm creation is successful/unsuccessful
-   ### Before
-   ### After
=> feat: add OD to healthcareProfessional degrees

.gitignore, plugins/vue-toastification-plugin.client.ts
✅ Resolves #1276
- Toast config globally set to position: top-center instead of the default position: top-right
- Minor: Added .idea for Jetbrains IDES to .gitignore
- Perform any action that triggers a toast. For e.g. on the Moderation dashboard or Add Doctor form submission
https://github.com/user-attachments/assets/95f4d6e4-3c27-47ce-8db7-ed1ceb42fe3e
=> fix: position toast to top-center
